import { GamePack } from './types';
import DevilIcon from './components/icons/DevilIcon';
import RelationshipIcon from './components/icons/RelationshipIcon';
import DatingIcon from './components/icons/DatingIcon';
import ConfessionIcon from './components/icons/ConfessionIcon';

export const AITA_CARDS: string[] = [
  "Your partner’s on a work trip. A friend posts a group photo from the pool — everyone’s drinking and laughing. But in the photo, your partner’s got their arm tightly wrapped around someone of the opposite sex.\nWhat do you do? Explain why.",
  "You notice a coworker texted your partner around 11 PM.\nIt’s a random question — but ends with a heart emoji.\nWhat do you do (and why)?\nA) Warn the coworker.\nB) Tell your partner to stop it.\nC) Confront them both in the same chat.",
  "There’s a paid app only your partner has. You use it more than they do, but every time you ask for the password, they refuse to tell you. One day, you start feeling suspicious.\nWhat do you do? Tell the details.",
  "You find a “Deleted Messages” folder on your partner’s phone — hundreds of old chats.\nIf you ask, it might break the trust between you. If you don’t, it’ll eat you alive. Looking without permission feels wrong.\nWhat do you do? Explain why.",
  "You open WhatsApp and notice your partner turned on “Delete all messages after 1 day.”\nThey never mentioned it. You realize they don’t want messages left on their phone anymore.\nIf you ask, you’ll look paranoid. If you don’t, you’ll keep obsessing.\nWhat do you do? Explain why.",
  "You’ve been dating for 3 years. Your loyal, faithful partner tells you they’re grabbing beers after work — with their ex.\nThey say, “We’re just friends now.”\nWhat do you do? Explain your reasoning.",
  "Your partner suddenly says, “Let’s share our live locations 24/7. I just want to know you’re safe… and I like keeping an eye on you.”\nWhat do you do? Explain in detail.",
  "You’re sitting next to your partner as they check Instagram DMs.\nYou notice them tilt the screen away from you — not once, but five or six times.\nIf you ask, it becomes a trust issue. If you don’t, it’ll drive you crazy.\nWhat do you do? Explain why.",
  "Your partner of one year says, “I think we should try an open relationship.”\nWhat do you do?\nA) Break up immediately.\nB) Agree right away.\nC) Say, “Let’s test it first.”",
  "The person you’ve secretly loved for years finally wants to be with you — but says, “I only do open relationships. If that’s okay, I’m yours.”\nWhat do you do? Explain your reasoning.",
  "Your mother-in-law came for a “short visit.”\nIt’s been two weeks — and she shows no signs of leaving.\nWhat do you do? Tell the details.",
  "Right now, your mother-in-law looks at you and says:\n“Can you make me a copy of your house key? Just in case.”\nYou know your partner wouldn’t mind — they’d even be happy if you said yes.\nWhat do you say?",
  "It’s your first married Christmas.\nWhose family do you spend it with?\nIf you go to yours, your partner’s side will be upset.\nIf you go to theirs, your family will feel hurt.\nWhat do you do? Explain your choice.",
  "Your partner’s family is wealthier than yours.\nYour father-in-law keeps making jokes that subtly put you down because of it.\nWhat do you do? Explain why.",
  "Your mother-in-law insists your baby should be named after your partner’s late father — a name you absolutely hate and that doesn’t fit your culture at all.\nWhat do you do? Explain your reasoning.",
  "You’re planning the wedding dinner.\nOne family insists the menu be vegan, the other says it must include halal meat.\nWhich do you choose and why?\nA) Disappoint your own family.\nB) Start off on the wrong foot with your partner’s.\nC) Ignore them both and do your own thing.",
  "You see your mother-in-law twice a week and talk once by phone.\nShe’s sweet, kind, you genuinely like her.\nBut every single time she brings up the same thing: “So… when’s the baby?”\nWhat do you do?",
  "Your dad offers serious financial help — enough to pay for your kid’s college one day.\nYour partner refuses it, saying they don’t want to “owe” anyone or feel small.\nThe fight grows — and now your relationship might end over this.\nWhat do you do?",
  "You feel your partner’s losing interest.\nThey’re always on their phone, distant, not intimate anymore.\nWhat do you do?\nA) Do nothing and just watch.\nB) Start a fight right away.",
  "You haven’t seen your partner in two months.\nWhenever you ask to meet, they say how much they love you — but claim they’re working late every night.\nWhat do you do?",
  "You’ve been stuck on the same issue for two years.\nWhenever you bring it up, your partner says, “That’s just who I am — accept it or leave.”\nPart of you agrees, part of you can’t stand it anymore.\nWhat do you do?",
  "There’s a problem from three years ago that you still can’t get over.\nWhenever you mention it, your partner sighs, “Ugh, are we still talking about this?”\nYou get it — but you can’t let it go.\nWhat do you do? Explain why.",
  "Your partner forgot your birthday.\nChoose one:\nA) Start a fight.\nB) Go quiet and give them the cold shoulder.\nC) Pretend it’s fine and die inside.",
  "You find out your partner tells their friends every detail about your relationship problems — every argument, every secret.\nWhat do you do?\nA) Blow up and confront them.\nB) Let it go — maybe it helps them release stress.",
  "It’s been two exhausting days — 16 hours of work, barely sitting down.\nOn the bus home, an old lady looks at you expectantly, clearly wanting your seat.\nWhat do you do?",
  "At a café, the waiter accidentally gives your order to the kid at the next table.\nThe kid looks at the plate and yells, “Mom, this looks so good!”\nYou’re starving.\nWhat do you do? Explain your choice.",
  "A sweet, cheerful kid has been screaming and playing loudly in the restaurant for 45 minutes straight.\nWhat do you do? Explain your reasoning.",
  "You’ve had horrible roommates before — but now you finally have a great one: kind, tidy, easygoing.\nExcept… they always leave hair all over the bathroom.\nThey’re also very sensitive, and one comment could ruin the vibe.\nWhat do you do?",
  "You’re in line at the supermarket.\nAn elderly person quietly cuts in front of you.\nIf you say something, everyone will think you’re rude.\nIf you don’t, you’ll miss your bus.\nWhat do you do?",
  "You and your partner manage your money perfectly — joint expenses, full transparency.\nBut one day, you get unexpected money — just enough to buy that thing you’ve been dreaming of.\nYour partner doesn’t know about it.\nWhat do you do?\nA) “It’s fine, I deserve this,” and buy it.\nB) “I could never do that to them,” and let it go.",
  "You and your partner never really talk about money — it doesn’t feel romantic.\nEverything’s fine financially.\nBut one day, you accidentally see a credit card statement from your partner’s “business trip.”\nThey spent a shocking amount that week.\nWhat do you do? Explain in detail.",
  "You lent a friend money four months ago.\nThey haven’t mentioned it once since.\nIt’s enough that asking might make you look stingy — but staying silent will eat you up inside.\nWhat do you do? Explain why.",
  "Your roommate borrowed your valuable item (like an electronic device) a couple of times — with permission.\nNow they just take it whenever they want, without asking.\nIt’s basically shared at this point.\nDo you say something and risk sounding petty — or let it go?",
  "At your wedding, four of your friends chipped in for an expensive gift.\nLater, you find out one of them secretly paid much less than the others — but you don’t know who.\nWhat do you do? Explain in detail.",
  "Your best friend seems a little too interested in your partner.\nThey laugh at every joke, touch their arm while talking, and always compliment them when you’re not around.\nWhat do you do? Explain what happens next.",
  "You’ve had a personal struggle for a long time — only one friend knows about it.\nThey tell your entire friend group in an attempt to “fix things.”\nIt works — but your secret is gone.\nWhat do you do?",
  "Two of your college friends are married — and you find out one of them is cheating.\nWhat do you do?",
  "It’s the night before your best friend’s wedding — and you just fell madly in love.\nThe person says, “I’m leaving tomorrow, you won’t see me for two years.”\nDo you go to your best friend’s wedding, or spend one last night with the love of your life?",
  "The love of your life finally wants to marry you.\nBut one of you wants kids — and the other doesn’t.\nWhat do you do?",
  "You’re with a rich, kind, wonderful person.\nThey want to marry you — but say, “My only condition is that you give up your dreams and stay home to raise our kids.”\nWhat do you do?",
];

export const RELATIONSHIP_ADVICE_CARDS: string[] = [
  "Your partner wants to quit their stable, high-paying job to become a full-time streamer. They currently have 12 followers. What advice do you give them?",
  "Your partner's best friend is openly rude to you and makes passive-aggressive comments. Your partner says, 'That's just how they are.' What's your advice for this situation?",
  "You and your partner have completely different 'love languages.' You need words of affirmation, they need acts of service. It's causing a major disconnect. Give some advice.",
  "Your partner is a terrible gift-giver. For your birthday, they got you a vacuum cleaner. It's a nice vacuum cleaner, but... What's the advice here?",
  "A friend comes to you saying, 'My partner and I fight constantly, but the makeup sex is incredible.' What advice do you give them?",
  "Your partner wants to get a large, very visible tattoo of your name. You've only been dating for six months. Advise them.",
  "Your partner's parents have offered a huge down payment for a house, but it comes with strings attached—like them having a key and 'dropping by.' What's your advice?",
  "You've discovered your partner has a secret credit card with a significant amount of debt. How do you advise they handle this?",
  "Your partner hates your hobby. They say it's 'cringey' and a 'waste of time.' How would you advise someone in this position?",
  "The spark is gone. You still love your partner, but the romance has fizzled out completely. Give some concrete advice to reignite it.",
  "Your partner is obsessed with a new, all-consuming diet and exercise plan. It's all they talk about, and it's making meals together impossible. What's your advice?",
  "Your long-distance partner rarely wants to video call. They prefer texting. You feel disconnected. What's your relationship advice?",
  "Your partner keeps in touch with all of their exes on social media, liking and commenting on their posts. It makes you uncomfortable. Give your advice.",
  "You and your partner have wildly different political views that are starting to cause serious arguments. What's the advice for navigating this?",
  "Your partner wants to combine finances, but you're a saver and they're a spender. How do you advise creating a system that works for both?",
  "Your partner is incredibly jealous and constantly questions who you're with and where you are. What's your advice for dealing with this?",
  "You want to get a dog. Your partner is firmly against it, saying they're a 'cat person.' Give advice on how to find a compromise.",
  "Your partner is a slob, and you're a neat freak. The state of your shared apartment is a constant source of tension. Advise on a solution.",
  "Your partner's friend is hitting on you. Do you tell your partner and risk their friendship, or handle it yourself? Give your advice.",
  "One of you snores. Loudly. The other isn't getting any sleep. What's the practical advice for this classic problem?",
  "Your partner wants to spend every holiday with their family, no exceptions. You feel like your family is always second place. Give your advice.",
  "Your partner has a terrible, time-consuming habit (like gaming 8 hours a day). How do you advise addressing it without starting a huge fight?",
  "You feel like you're doing all the emotional labor in the relationship—planning, remembering, and worrying. What's your advice?",
  "Your partner has become best friends with someone you really dislike. How do you advise handling this situation gracefully?",
  "You accidentally said 'I love you' first, and your partner responded with 'Thank you.' Give advice on how to recover from this.",
  "Your partner is a terrible cook but insists on cooking for you every night. The food is... bad. What's your advice?",
  "You're ready for marriage, but your partner says they 'don't believe in labels.' What's the advice for this impasse?",
  "Your partner and your best friend hate each other. You're constantly caught in the middle. Give your best advice.",
  "Your partner wants to move to a new city for a 'dream job' that feels like a long shot. You'd have to give up your great job. What's your advice?",
  "Your partner is a social butterfly, and you're an introvert. They always want to go out; you always want to stay in. Advise a compromise.",
  "You think your partner is spending too much time with a 'work spouse.' How do you advise bringing this up without sounding accusatory?",
  "Your partner is a picky eater, and it limits your dining experiences and your ability to cook new things. What's the advice?",
  "One of you wants kids in the next year. The other wants to wait at least five more years. Give your advice on this major life decision.",
  "Your partner has a friend who is a known cheater. You don't trust them and don't want them around. What's your advice?",
  "Your partner constantly posts unflattering pictures of you on social media, even after you've asked them to stop. What's your advice?",
  "Your partner has a different definition of 'clean' than you do. Their version is 'not actively hazardous.' Give your advice for living together.",
  "You feel like your partner's family doesn't like you. Every gathering is awkward and tense. What's your advice?",
  "Your partner's communication style is very blunt, and it often hurts your feelings. They say they're 'just being honest.' Give your advice.",
  "You've been together for years and your partner still hasn't introduced you to their core group of friends. What's your advice?",
  "Your partner is overly critical of your driving. Every car ride is a stressful experience. Give your advice."
];

export const DATING_CARDS: string[] = [
  "Tell us about your most awkward first date. Spare no details.",
  "Describe the worst pickup line someone has ever used on you, and what happened next.",
  "Share the story of a date that seemed perfect on paper but was a total disaster in reality.",
  "Recount the most cringeworthy thing you've ever done to impress a crush.",
  "Tell the story of the best first kiss you've ever had.",
  "Describe a time you completely misinterpreted the signals on a date.",
  "Share a hilarious story about meeting the parents for the first time.",
  "What's the biggest red flag you ignored in a person you were dating? Tell the story.",
  "Tell us about a time you were 'catfished' or the person looked nothing like their profile pictures.",
  "Describe your most memorable 'friend zone' moment—either giving or receiving.",
  "Share a story about a date with someone who had a really weird or annoying habit.",
  "Recount a time a date went so well it felt like a movie scene.",
  "What's the most elaborate lie you've ever told while dating? Did you get caught?",
  "Tell us about your most spectacular dating app fail.",
  "Describe a date where you had absolutely nothing in common with the other person.",
  "Share a story about a time you tried to cook for a date and it went horribly wrong.",
  "Recount the moment you knew a relationship was definitely over.",
  "What's the funniest misunderstanding you've had with someone you were dating?",
  "Tell us about a time you tried a grand romantic gesture that completely backfired.",
  "Describe a date that was saved from disaster at the last minute.",
  "Share a story about dating someone your friends absolutely hated.",
  "What's the weirdest place someone has ever taken you on a date?",
  "Tell the story of the one that got away.",
  "Describe a time you had to make a dramatic escape from a terrible date.",
  "Recount a story of a double date that went hilariously wrong.",
  "What's the most embarrassing thing that's happened to you in front of a date?",
  "Share a story about accidentally calling a date by an ex's name.",
  "Tell us about a time you went on a date with someone who was clearly still in love with their ex.",
  "Describe the biggest difference between your dating profile and your real self. Tell a story about it.",
  "Recount a time you went on a date with a 'know-it-all.'",
  "Share a story about a date where you had a major wardrobe malfunction.",
  "What's the most surprising thing you've learned about someone on a first date?",
  "Tell us about the moment you realized you were falling in love.",
  "Describe a time you were set up on a blind date by a friend. How did it go?",
  "Share a story about a date who brought their pet along unannounced.",
  "Recount a time you had a powerful, instant connection with someone.",
  "What's the most over-the-top, extravagant date you've ever been on?",
  "Tell a story about a date with a terrible sense of humor.",
  "Describe a time you thought you were being ghosted, but there was a perfectly good explanation.",
  "Share the story of the first time you said 'I love you.'"
];

export const OFF_MY_CHEST_CARDS: string[] = [
  "Confess a petty grudge you've held for way too long.",
  "What's a secret you've kept from your parents your entire life? Confess it.",
  "Confess a time you were completely in the wrong during an argument but refused to admit it.",
  "What's a social event you secretly wanted to be cancelled and were thrilled when it was? Confess.",
  "Confess a lie you told that spiraled out of control.",
  "What's something you pretended to like to impress someone? Come clean.",
  "Confess a time you snooped through someone's phone or belongings. What did you find?",
  "What's a nickname you have for someone behind their back? Confess it.",
  "Confess a time you 'accidentally' broke something that belonged to someone else and never told them.",
  "What's a popular movie, show, or book that you pretend to have seen/read but haven't? Confess.",
  "Confess the most childish thing you've done as an adult.",
  "What's a secret you know about someone in this room? (You don't have to name them!) Confess the secret.",
  "Confess a time you re-gifted a present. Who was it from and who did it go to?",
  "What's a food you secretly hate but eat to be polite? Confess.",
  "Confess the most embarrassing thing you've ever done while drunk.",
  "What's an irrational fear you have? Confess it.",
  "Confess a time you faked being sick to get out of work, school, or a social commitment.",
  "What's a secret purchase you've hidden from a partner or roommate? Confess.",
  "Confess a time you eavesdropped on a conversation and heard something juicy.",
  "What's a weird habit you have when you're alone? Confess.",
  "Confess a time you took credit for someone else's work or idea.",
  "What's a strong opinion you hold but are too afraid to share publicly? Confess it.",
  "Confess a time you were incredibly jealous of a friend's success.",
  "What's a song or artist that is your ultimate guilty pleasure? Confess.",
  "Confess a time you blamed a fart on someone else (or an animal).",
  "What's something you borrowed and never returned? Confess.",
  "Confess a secret crush you've had on a friend's partner or sibling.",
  "What's the biggest thing you've gotten away with? Confess.",
  "Confess a time you judged someone on their appearance and were later proven completely wrong.",
  "What's a piece of common knowledge you only learned embarrassingly late in life? Confess.",
  "Confess a recurring, weird dream you have.",
  "What's one thing you wish you could apologize for but never have? Confess the situation.",
  "Confess a time you were a terrible houseguest.",
  "What's a promise you broke? Confess.",
  "Confess a time you cheated in a game and got away with it.",
  "What's a cringey memory from your past that keeps you up at night? Confess it.",
  "Confess something you do that you know annoys your partner, family, or roommates, but you do it anyway.",
  "What's a fantasy you have about a different life? Confess.",
  "Confess a time you were a 'Karen' or 'Ken' in a public situation.",
  "What's the one secret you've sworn you would take to the grave? (Maybe confess a slightly smaller one instead)."
];


export const GAME_PACKS_DATA = {
  [GamePack.AITA]: {
    title: 'Am I The A**hole?',
    setupTitle: "Ready to find the biggest A*shole?",
    description: "Defend your questionable choices in hilarious and tricky scenarios.",
    cards: AITA_CARDS,
    judgeTitle: (playerName: string) => `Is ${playerName} the a**hole?`,
    positiveVote: "YOU'RE THE A**HOLE",
    negativeVote: "NOT THE A**HOLE",
    winnerTitle: "Tonight's Biggest A**hole is...",
    Icon: DevilIcon,
  },
  [GamePack.RELATIONSHIP]: {
    title: 'Relationship Advice',
    setupTitle: "Ready to crown the best Relationship Guru?",
    description: "Give your best advice on tricky relationship dilemmas to prove you're the expert.",
    cards: RELATIONSHIP_ADVICE_CARDS,
    judgeTitle: (playerName: string) => `Did you like ${playerName}'s advice?`,
    positiveVote: "LOVED THE ADVICE",
    negativeVote: "TERRIBLE ADVICE",
    winnerTitle: "Tonight's Best Relationship Guru is...",
    Icon: RelationshipIcon,
  },
  [GamePack.DATING]: {
    title: 'Dating',
    setupTitle: "Who's the best storyteller?",
    description: "Share your most hilarious, awkward, and heartwarming dating stories.",
    cards: DATING_CARDS,
    judgeTitle: (playerName: string) => `Did you like ${playerName}'s story?`,
    positiveVote: "LIKED IT",
    negativeVote: "DIDN'T LIKE IT",
    winnerTitle: "Tonight's Best Storyteller is...",
    Icon: DatingIcon,
  },
  [GamePack.OFF_MY_CHEST]: {
    title: 'Confessions',
    setupTitle: "Who has the courage to confess?",
    description: "Share deep secrets and confessions you've been holding back.",
    cards: OFF_MY_CHEST_CARDS,
    judgeTitle: (playerName: string) => `Did ${playerName} truly confess?`,
    positiveVote: "CONFESSION ACCEPTED",
    negativeVote: "HELD BACK",
    winnerTitle: "Tonight's Bravest Confessor is...",
    Icon: ConfessionIcon,
  },
};
