export const CARDS: string[] = [
  "%% shared a friend's Netflix password with others without asking. Explain why it wasn't a big deal.",
  "%% left a group chat without telling anyone. Defend your decision.",
  "%% scheduled a party on a weekday night and expected everyone to come. Justify it.",
  "%% forgot a close friend’s birthday but posted a meme that day. Defend yourself.",
  "%% borrowed something and returned it a week late. Explain why it was fine.",
  "%% cancelled plans last minute because you were ‘not in the mood’. Make your case.",
  "%% used the household’s last bit of milk and didn’t replace it. Defend.",
  "%% kept a gift receipt and exchanged the gift for cash. Explain.",
  "%% posted a private conversation screenshot in a friend group. Why is that okay?",
  "%% brought an extra guest to a dinner without asking. Defend it.",
  "%% took credit for a team idea because you presented it. Justify.",
  "%% told a harsh truth at the worst possible time. Explain why honesty mattered.",
  "%% left dishes in the sink ‘to soak’ for two days. Defend.",
  "%% told someone their outfit wasn’t appropriate for the event. Defend.",
  "%% refused to lend money to a friend. Explain why that was responsible.",
  "%% brought outside food to a friend’s dinner party. Make the case.",
  "%% skipped a wedding to save money. Defend your priorities.",
  "%% didn’t answer messages for 48 hours to ‘reset’. Explain.",
  "%% told a friend their new partner is a red flag. Justify.",
  "%% didn’t offer your seat to someone on public transport. Defend yourself.",
  "%% re-gifted something to another friend. Explain why it’s efficient.",
  "%% muted a friend’s stories and they found out. Defend.",
  "%% asked everyone to remove shoes at your place. Make the case.",
  "%% reported a noisy neighbor instead of talking first. Explain.",
  "%% refused to babysit because it’s not ‘your thing’. Defend.",
  "%% brought work laptop on vacation and kept checking it. Justify.",
  "%% corrected someone publicly instead of privately. Defend.",
  "%% didn’t split the bill evenly because you ate less. Explain.",
  "%% told a friend they can’t bring their dog. Make the case.",
  "%% left a date early because there was no chemistry. Defend.",
  "%% didn’t invite a friend to a small gathering. Explain.",
  "%% asked roommates to label food items. Defend why it’s normal.",
  "%% said ‘no kids’ for your birthday. Make the case.",
  "%% told someone a hobby of theirs is boring. Explain.",
  "%% refused to share your location with partner/friends. Defend.",
  "%% brought up politics at dinner. Explain why it was relevant.",
  "%% changed group trip plans without getting consensus. Defend.",
  "%% used speakerphone in a semi-public place. Explain.",
  "%% parked slightly over the line to avoid door dings. Defend.",
  "%% left a party without saying goodbye. Explain.",
  "%% asked for quiet hours at home after 10pm. Defend.",
  "%% turned down helping someone move. Make your case.",
  "%% asked a guest to leave shoes outside in the rain. Defend.",
  "%% didn’t answer the door for an unexpected visitor. Explain.",
  "%% brought a store-bought dessert to a ‘homemade’ dinner. Defend.",
  "%% refused to swap seats on a plane. Explain why that’s fair.",
  "%% asked for separate checks at the last second. Defend.",
  "%% corrected someone’s pronunciation repeatedly. Explain.",
  "%% said no to lending your car. Defend.",
  "%% set a hard curfew for game night. Explain."
];
